import { ProductType } from '@wns/features/CatalogPage/components/CatalogList/model/ProductTypes';

export const mockProducts: ProductType[] = [
  {
    id: '1',
    name: 'КОЛЬЦО ОРБИТА',
    description: 'Минималистичное кольцо из титана с матовой отделкой',
    price: 12900,
    category: 'Кольца',
    tags: ['НОВИНКА'],
    image: '/placeholder.png',
  },
  {
    id: '2',
    name: 'СЕРЬГИ ГЕОМЕТРИЯ',
    description: 'Легкие титановые серьги с геометрическим дизайном',
    price: 9800,
    category: 'Серьги',
    tags: [],
    image: '/placeholder.png',
  },
  {
    id: '3',
    name: 'БРАСЛЕТ ВОЛНА',
    description: 'Гибкий титановой браслет с волнообразным дизайном',
    price: 15600,
    category: 'Браслеты',
    tags: [],
    image: '/placeholder.png',
  },
  {
    id: '4',
    name: 'КУЛОН МИНИМАЛ',
    description: 'Титановый кулон с минималистичным дизайном',
    price: 8400,
    category: 'Кулоны',
    tags: [],
    image: '/placeholder.png',
  },
  {
    id: '5',
    name: 'КОЛЬЦО ЗАТМЕНИЕ',
    description: 'Титановое кольцо с черным матовым покрытием',
    price: 14200,
    category: 'Кольца',
    tags: ['ЛИМИТИРОВАННАЯ СЕРИЯ'],
    image: '/placeholder.png',
  },
  {
    id: '6',
    name: 'СЕРЬГИ КАСКАД',
    description: 'Длинные титановые серьги с каскадным дизайном',
    price: 11300,
    category: 'Серьги',
    tags: ['НОВИНКА'],
    image: '/placeholder.png',
  },
];
